### ISSUE TITLE
xpipe is struggling when loading a lot hosts and freeze

### ISSUE THREAD

**Issue by Austrum-lab** [xpipe-io/xpipe#431]
Hello!

OS:
- Linux (Debian, Gnome DE, Wayland)
- macOS 15.2 (m3 pro)
xpipe version: 14.2

Here's the issue. xpipe struggling to render all hosts when there are a lot of them. It just starting to use a lot of resources and freeze after some time.
It happens with 1500+ resources in the folder I suppose?

When I try to load a folder with ~1000 resources it straggling for a time, but load everything. After it is rendered it's kinda smooth (until I go to another folder and back). Which is also seems not good.
When it's a folder with 1600 resources the issue happens.

I have this configuration:
Every host contains a shell environments and there are 2 of them - both bash, 1 of them is using script to do 'sudo -i' after login. So there are around 750 hosts at all (1:4).
Each host goes through ssh gateway and uses a key-based (file) local identity (they are the same).

For a small number of hosts with my configuration there are no issues and freezes.

I tried to test my config at another system (mac m3pro) (by moving .xpipe directory) - it's completely the same behavior.

I also tried to enable performance mode - the same.

![Image](https://github.com/user-attachments/assets/d143690d-caf7-412a-bbde-6ff3abb61223)
![Image](https://github.com/user-attachments/assets/af241078-eb95-4dda-9419-58b4bb955337)

**Comment by crschnick** [comment]
That is somewhat of a known issue, and it relates to having that many folders. I think the amount of connections doesn't really matter that much.

You can try using https://github.com/xpipe-io/xpipe-ptb, this problem should be fixed to some degree in there. I guess if you want to keep using the normal connections in the PTB, you can copy the ~/.xpipe directory to ~/.xpipe-ptb

**Comment by Austrum-lab** [comment]
I just tried 15.0-27 version, same =/

Also, I think the issue relates to that folder was opened first. If I open first big folder (with 1600) resources it loads (but struggling) and after that folder with 1000 resources it will crash on it.
Like for example for folders from my screenshot in order (96 - ok) - (1608 - ok) - (1072 - not ok). Maybe it depends on how many resources, folders, connections were already rendered in session.

Anyway, is there any workaround for my config? I can live with just ssh connections (but through ssh gateway).

**Comment by crschnick** [comment]
On an unrelated note, is it even possible to efficiently navigate it if you have that many connections (assuming that there would not be any performance issue)? I can look into optimizing the existing display, or maybe change it up for larger sets of connections. May be a different way to view connections

**Comment by Austrum-lab** [comment]
It doesn't really crash. It just starts to use a lot more resources (cpu), freeze and after some time OS starts suggesting to kill it.
No messages, no logs as I see.
I forgot to mention - on search it also freeze


> I think as a workaround, if you create nested subfolders and only put a few hundred connections in each one, it should mitigate this somehow.

I think it will also freeze on search with this config)


> On an unrelated note, is it even possible to efficiently navigate it if you have that many connections (assuming that there would not be any performance issue)?

With search yes) most of my connections are sorted by project names and types (in their name)

**Comment by crschnick** [comment]
Alright, I will look into this. Probably need to set up a script first to generate that many connections.

I think some issues, I like the workaround still freezing when using the search, can be fixed pretty easily. But in general, I have to think about how to handle larger connection sets better and have to do some experimentation.

**Comment by crschnick** [comment]
But in general, about having that many shell environments to run sudo -i, this can also be done by creating a script and set it to run on init at New ... -> Script

**Comment by Austrum-lab** [comment]
I recreated my configs with only hosts without shells folders in them. (god thanks I know bash and don't need to do it manually)
Now it works fine (but still struggles a bit while you go between directories).
~$ ls -alht ~/.xpipe/storage/stores/ | wc -l
780



> But in general, about having that many shell environments to run sudo -i, this can also be done by creating a script and set it to run on init at New ... -> Script

Nah, I'd like to connect to hosts with my user. Just it's nice to have opportunity to do it then it need)
My 1st think was to create 3 shells (sh bash sudo) for the same purpose)

**Comment by crschnick** [comment]
So I will look into optimizing the performance.

About the scripting, if you make it a runnable script instead, you can call it from the scripts button on every connection and can choose that way whether you want to connect normally or with sudo

![Image](https://github.com/user-attachments/assets/4c1c92c4-4e58-4070-84cc-2abfaab6a31b)

**Comment by crschnick** [comment]
So I published another PTB build. I think I eliminated all the performance issues on the backend, so any slowdown, freezes, and crashes are now caused by the frontend renderer not keeping up with the load. Fixing that requires some more work

**Comment by crschnick** [comment]
Actually, improving the rendering performance was easier than expected. That is also now improved in the latest PTB build.

**Comment by Austrum-lab** [comment]
I tied latest ptb version (15.0-31)
It looks like it become to work a bit faster, but original issue and lags still exist.

**Comment by crschnick** [comment]
Alright I think I'm able to reproduce it now fully. It seems like it is very dependent on switching between one folder to another were both have a lot of connections. If I switch from the first to an empty one, and then to the second, it works acceptably.

**Comment by crschnick** [comment]
I published another PTB build with several performance fixes for this case. Let me know if that improves this situation

**Comment by Austrum-lab** [comment]
Sorry for making you wait, haven't had time on weekdays.

The latest PTB build (15.0-49) works significantly better. It thinks on load a bit (about 15 secs), but after that work well (loading between folders about 2-5sec and no freezes). Search also works.
And I'm talking about my 1st version of folders and configs (with 4 folders for a host - a host, shells, bash, sudo).

There's an issue with icons in big folders - they just don't show up, is it expected behavior?

**Comment by crschnick** [comment]
That is good news.
 
About the icons, I try to remove them for large folders. I can readd them back and you can check whether there is a difference

**Comment by Austrum-lab** [comment]
> I can readd them back and you can check whether there is a difference

Sure thing, I can test if it's needed.

Also, there's a bug with the custom icon - when I try to use a custom icon for something after xpipe restart it will be back to an old icon (but on .json config it is still the new icon). It exists on both versions (prod and ptb).
Like for 'sudo' connections I'm trying to use
"icon" : "shoko-server",

May I ask if there will be updates on prod version any soon or do I need to wait 15 version to be released and stay on ptb for now?

**Comment by Austrum-lab** [comment]
> Also, there's a bug with the custom icon - when I try to use a custom icon for something after xpipe restart it will be back to an old icon (but on .json config it is still the new icon). It exists on both versions (prod and ptb).
> Like for 'sudo' connections I'm trying to use
> "icon" : "shoko-server",

Just checked another time and bug is gone, so nevermind)

**Comment by crschnick** [comment]
v15 is planned to release on Tuesday

**Comment by crschnick** [comment]
You can try the latest PTB to see whether showing or not showing the icons makes a difference

**Comment by Austrum-lab** [comment]
> You can try the latest PTB to see whether showing or not showing the icons makes a difference

It works fine, can't really tell if with or without icons any difference.

**Comment by crschnick** [comment]
Then I can keep the icons

**Comment by crschnick** [comment]
This is now released
