### ISSUE TITLE
SSH config with branching

### ISSUE THREAD

**Issue by unleashit** [xpipe-io/xpipe#502]
xpipe doesn't seem to handle branching within an SSH config. For example:

```
Host 1.1.1.1 #example
  Match User user1
     IdentityFile path\to\key
     Port 2222
  Match User user2
    IdentityFile path\to\key
    Port 2223
```
The use case here is for example to have a normal SSH user, and then another for a service/container like GItlab or Gitea that require their own additional SSH server.

Currently, the host shows up in new pipe, but the discovery for the sub connections fails with:

```
io.xpipe.core.process.ProcessOutputException: Shell opener command was unsuccessful:
ssh: connect to host <redacted> port 22: Connection refused
at io.xpipe.core.process.ProcessOutputException.withPrefix(ProcessOutputException.java:29)
at io.xpipe.ext.proc.util.e.cf(SourceFile:192)
at io.xpipe.ext.proc.n.p(SourceFile:1689)
at io.xpipe.ext.proc.ssh.o.p(SourceFile:113)
at io.xpipe.ext.proc.n.D(SourceFile:587)
at io.xpipe.ext.proc.n.start(SourceFile:276)
at io.xpipe.app.ext.ShellSession.start(ShellSession.java:30)
at io.xpipe.core.store.SingletonSessionStore.startSessionIfNeeded(SingletonSessionStore.java:54)
at io.xpipe.app.ext.ShellStore.getOrStartSession(ShellStore.java:27)
at io.xpipe.app.util.ScanDialogComp.lambda$onUpdate$3(ScanDialogComp.java:100)
at io.xpipe.app.util.BooleanScope.executeExclusive(BooleanScope.java:22)
at io.xpipe.app.util.ScanDialogComp.lambda$onUpdate$4(ScanDialogComp.java:97)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:45)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:22)
at java.lang.VirtualThread.run(VirtualThread.java:329)
```

It tries to connect on port 22, which is not open. I also tried giving each branch an explicit HostName, but that didn't work.

I'm not sure if this would be complicated to implement. I haven't tried manually creating connections to each of these, but I will and maybe that can be a workaround.

**Comment by crschnick** [comment]
Can you try whether https://github.com/xpipe-io/xpipe-ptb works for you, I fixed a few things relating to that

**Comment by unleashit** [comment]
Thanks so much for your efforts, but so far it didn't fix it for me. With the above config, it still tries to connect on port 22 when discovering connections. I played around with the SSH config and tried for example:

```
Host 1.1.1.1
  Port 2222 # Attempting to set a default port for the find avail connections process...
  Match User user1
     IdentityFile path\to\key
     Port 2222
  Match User user2
    IdentityFile path\to\key
    Port 2223
```
SSH sessions work fine for both users/ports in the terminal, but not with xpipe.

Perhaps the problem is because there is no default User for the "find available connections" session. I don't think (AFAIK) I can set one in the SSH config and still have the matching work.

That said, I found I was able to create the connections manually just fine. So if you have bigger priorities, it's really not a problem. Its mainly a matter of aesthetics so the connections appear automatically, in the right place and without and error when auto exploring a config file.

**Comment by crschnick** [comment]
So just to confirm, you added the SSH config connection and configured it like this? 

![Image](https://github.com/user-attachments/assets/db9da978-fe71-4cc7-b086-0dfdf1222f6c)

It should now connect with `user1@<host name>`.

**Comment by unleashit** [comment]
Ah, for some reason I didn't think to add the user there. Before, I think it found it automatically from the config. Anyway, it's working now, thanks again! We can close the issue unless you want to keep it open.

**Comment by crschnick** [comment]
This is now released in 15.8

**Comment by unleashit** [comment]
Just for completeness, there are still some (minor) issues with this, probably having to do with how the ssh config is being parsed.

For some reason, xpipe is using the port designated in a branched host as the port of the other unrelated host(s) in the config file. Here's an example: 

```bash
Host host1
  HostName 1.1.1.1 #example
  IdentityFile C:\path\to\key
  User someuser
Host host2
  Port 2222
  Match User user1
    HostName 2.2.2.2
    IdentityFile C:\path\to\key
    Port 2222
  Match User user2
    HostName 2.2.2.2
    IdentityFile C:\path\to\key
    Port 2223
``` 
In this config, connecting to host2 works after configuring a default user in xpipe. But host1 for some reason tries to connect to the default port of host2 which fails because it needs port 22.

For my purposes I was able to fix by explicitly adding Port 22 to host1. But I thought I'd let you know that there seems to be a bit of weirdness going on still. It's pretty minor, but I thought I'd mention since you were recently working on it.

**Comment by crschnick** [comment]
So that it doesn't happen for me with the example you posted. If I run it like that, host1 will use Port22. Is your actual config using something different?

**Comment by crschnick** [comment]
Any updates on this? I can look into it if I have a config file that reproduces this, because the example works for me

**Comment by unleashit** [comment]
Sorry for dropping the ball here. To answer your question from before, my config has several additional entries, and the actual variables are not the same. But the top two have the same template. Here's the whole thing with only vars changed (at list my Windows one which xpipe uses):

```
Host host1
 # had to add Port 22 here otherwise xpipe tried to connect via the port host2 was is using (plain SSH did not have the issue)
  HostName x.x.x.x
  IdentityFile C:\path\to\key
  User someuser
Host host2
  Port 2222 # this was also necessary, or xpipe would choose 22
  Match User host2user1
    HostName x.x.x.x
    IdentityFile C:\path\to\key
    Port 2222
  Match User host2user2
    HostName x.x.x.x
    IdentityFile C:\path\to\key
    Port 2223
Host host3
 HostName x.x.x.x
 IdentityFile C:\path\to\key
Host host4
 HostName x.x.x.x
 IdentityFile C:\path\to\key
Host github.com
 IdentityFile C:\path\to\key
Host gitlab.com
 IdentityFile C:\path\to\key
```
 
I'll tinker around with this a bit more tonight. I no longer have "host1" but I should still have enough to play around with.

**Comment by crschnick** [comment]
This looks to be an OpenSSH issue, it doesn't use the correct default port if none is specified. I will implement a workaround for this behavior so that it at least works correctly from XPipe

**Comment by unleashit** [comment]
So I just had a chance to play with it some more. On of the servers in my config is gone (host1), but I now have slightly different issues. All of them are solvable by adding explicit users and ports to the config (ssh config file). I don't think this is a big issue (definitely not for me personally), but I think it must be on the xpipe side because everything always works with normal ssh sessions.

I spent a little time on this (including having fight with fail2ban...), and ran into a few different problems. On one server (host3), it was trying to connect using my windows username, even though no ssh user is named after that. I can only guess that it somehow got it from the path to the ssh key: C:\Users\<user>\.ssh\<keyfile> since its nowhere else (haven't set up any xpipe identities either). Depending on whether I added a default port to host1 (the branched),  This was only solved by explicitly added `User root` to the config file. The issue of needing a default port for the branched host also happens only in xpipe.

In any case, I think this app is pretty useful and appreciate what you're doing!

**Comment by crschnick** [comment]
Just to make sure that I'm not fundamentally missing something here. XPipe doesn't do anything else than you would do if you do `ssh user@host` or just `ssh host` if you are using a config entry. It doesn't have its own SSH implementation, it just calls your OpenSSH client.

So any problems you encountered with these config issues should also happen if you run the commands manually in a terminal without xpipe, unless there is something I am missing with the environment somehow changing the behavior in unintended ways.

**Comment by unleashit** [comment]
Do you think openssh could behave differently in cmd.exe vs Powershell? Because that's the only difference I can think of between what I'm doing and xpipe. Xpipe is using cmd.exe (I think I can get it to use Powershell, but it configures cmd.exe automatically)

Aside from that, I admit it's a bit of a pain testing this because of fail2ban (if I test more I'll just disable it).

**Comment by crschnick** [comment]
You can go to Settings -> Connections -> Use fallback shell to make XPipe use powershell. But it shouldn't make a difference

You can also check the commands it runs at Settings -> Troubleshoot -> Show log files

For example, the initial issue with host1 using the host2 port if no port was explicitly specified also happens for me in a terminal without XPipe. So I'm pretty sure this is an OpenSSH bug. The best I can do is work around OpenSSH bugs, which I have done with several now. For example, this specific port issue is already fixed for the next release.

**Comment by unleashit** [comment]
Ok sounds good. I admit, that fail2ban kind of voided some of my experimenting before I realized it was putting me in jail. Still, it seems pretty repeatable that xpipe wants to use my windows user name to log in to a host and doesn't try the default "root'. Here's the related command from the logs in case it offers any clues. The same command 

```
11:19:19:867 - info: Starting sub shell ... {
    manageParent=false
    command=$env:DISPLAY='localhost:0.0';$env:SSH_ASKPASS_REQUIRE='force';$env:SSH_ASKPASS='C:\Users\<windowsuser>\AppData\Local\XPipe\bin\xpipe.exe';$env:ASKPASS_PREFIX='[ssh]';$env:ASKPASS_REQUEST='xxxx-xxxx';$env:ASKPASS_SECRET='xxxx-xxxx';$env:BEACON_PORT='21721';ssh -oNumberOfPasswordPrompts=3 "x.x.x.x" -oStrictHostKeyChecking=accept-new -oIgnoreUnknown=RemoteCommand -oRemoteCommand=none -T -oNoHostAuthenticationForLocalhost=yes -i 'C:\Users\<windowsuser>\.ssh\<key>' -oIdentitiesOnly=yes
    elevated=false
}
```

**Comment by crschnick** [comment]
So by default, Windows OpenSSH uses the system username if none is specified. Are you using the Windows OpenSSH or something like the git bash ssh or cygwin ssh?

**Comment by unleashit** [comment]
Using Windows OpenSSH. As far as I'm concerned though, these issues are not a big deal and are easily solved. Just trying to be helpful, but I might be erring on the side of being over thorough here...

**Comment by crschnick** [comment]
Yeah, I'm just trying to figure out where the different behavior comes from as that isn't expected.

If you say that XPipe doesn't use the default user 'root', does that mean that it uses root in your terminal if you run that ssh config without a username? Because that is definitely not standard behavior

Can you run something like `where ssh` in cmd?

**Comment by unleashit** [comment]
OK I think I figured out the disconnect on this one is I've been assuming that "xpipe" uses a default user of root if one isn't provided in the config. I'm not thinking that was a bad assumption. I just added manually added root within xpipe and now it works. I think I resisted doing that because a) one of my configs uses branching, and I just assumed I didn't need to. I definitely do specify the user when I manually ssh in the terminal like ssh root@x.x.x.x.

**Comment by crschnick** [comment]
Ok that explains the difference. If you specifiy the same user as in the terminal, it should behave exactly the same now
