### ISSUE TITLE
Using a custom icon git repo, causes icons to be lost on restart of XPipe

### ISSUE THREAD

**Issue by jackedproxy** [xpipe-io/xpipe#674]
If using a custom icon git repo, all my set icons are lost when the application restarts, resulting in the following:
<img width="384" height="402" alt="Image" src="https://github.com/user-attachments/assets/5f5f56b8-c1a7-4174-8344-4c9cdcf9beba" />

Forcing a refresh of the icons alone doesn't fix it.
What seems to fix it is forcing a refresh AND launching each connection one-by-one, which then refreshes the icon.

Git repos I've tested:
https://github.com/loganmarchione/homelab-svg-assets.git
https://github.com/homarr-labs/dashboard-icons.git
https://github.com/akveo/eva-icons.git

**Comment by crschnick** [comment]
This is now fixed in 18.4

**Comment by furkantarikgocmen** [comment]
this issue still exists (professional 20.1 and since version 17 or 18 i dont sure, i thought its a feature but looks like its not :) ) @crschnick 

<img width="589" height="164" alt="Image" src="https://github.com/user-attachments/assets/adb7512b-f5ad-48ae-a500-38b801ae2378" />

<img width="74" height="204" alt="Image" src="https://github.com/user-attachments/assets/351073c3-7099-4fa1-8dec-0d9b02de3b57" />

**Comment by crschnick** [comment]
@furkantarikgocmen This should now be fixed properly in 20.2. There was a race condition

**Comment by furkantarikgocmen** [comment]
Seems fixed, kudos 🙌
